# Generated by Django 4.2.6 on 2023-11-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record_is_completed_alter_record_actual_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
