# Generated by Django 4.2.6 on 2023-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default=0, max_length=50, verbose_name='Время на выполнение'),
            preserve_default=False,
        ),
    ]
