# Generated by Django 4.2.6 on 2023-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_record_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='on_delete',
            field=models.BooleanField(default=True),
        ),
    ]
